In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [8]:
df = pd.read_csv('Most Streamed Artists on Spotify (17_07_2026) V1.1.csv')

In [9]:
df.describe()

,Debut Year,Total Streams (in millions),Lead Streams (in millions),Feature Streams (in millions),Solo Streams (in millions),% of Solo Streams,Collaborative Streams (in millions),% of Collaborative Streams
count,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000
mean,2005.346000,16817.610200,12141.734000,4681.289000,8324.397600,50.613084,8493.212600,49.386916
std,13.312578,14845.197632,11844.675186,5952.827762,9589.010168,33.762147,9612.491536,33.762147
min,1939.000000,6972.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2001.750000,8768.175000,6489.750000,696.500000,2519.775000,20.117951,2015.650000,16.860219
50%,2009.000000,11923.250000,8716.350000,3005.600000,6472.950000,47.062829,6592.250000,52.937171
75%,2014.000000,18020.050000,13456.900000,6093.350000,10115.550000,83.139781,11019.575000,79.882049
max,2023.000000,137492.100000,126177.300000,43710.500000,113421.500000,100.000000,84168.200000,100.000000

In [10]:
df.columns

Index(['Artist Name', 'Sex', 'Country of Origin', 'Primary Language',
       'Primary Genre', ' Artist Type', 'Debut Year',
       'Total Streams (in millions)', 'Lead Streams (in millions)',
       'Feature Streams (in millions)', 'Solo Streams (in millions)',
       '% of Solo Streams', 'Collaborative Streams (in millions)',
       '% of Collaborative Streams'],
      dtype='str')

In [18]:
df.columns = df.columns.str.strip()
df[df["Artist Name"] == "Chris Brown"].head(10)

,Artist Name,Sex,Country of Origin,Primary Language,Primary Genre,Artist Type,Debut Year,Total Streams (in millions),Lead Streams (in millions),Feature Streams (in millions),Solo Streams (in millions),% of Solo Streams,Collaborative Streams (in millions),% of Collaborative Streams
21,Chris Brown,Male,United States,English,R&B,Solo,2005,43963.8,24455.7,19523.9,12219.3,27.794003,31744.5,72.205997

In [19]:
df[df["Primary Genre"]=="R&B"]

,Artist Name,Sex,Country of Origin,Primary Language,Primary Genre,Artist Type,Debut Year,Total Streams (in millions),Lead Streams (in millions),Feature Streams (in millions),Solo Streams (in millions),% of Solo Streams,Collaborative Streams (in millions),% of Collaborative Streams
3,The Weeknd,Male,Canada,English,R&B,Solo,2009,95703.2,77189.4,18513.8,51020.0,53.310652,44683.2,46.689348
21,Chris Brown,Male,United States,English,R&B,Solo,2005,43963.8,24455.7,19523.9,12219.3,27.794003,31744.5,72.205997
33,SZA,Female,United States,English,R&B,Solo,2012,38879.6,25267.5,13627.2,19804.6,50.938281,19075.0,49.061719
39,Khalid,Male,United States,English,R&B,Solo,2016,35727.2,18499.9,17234.4,12520.6,35.045008,23206.6,64.954992
71,Ty Dolla $ign,Male,United States,English,R&B,Solo,2011,26465.2,5073.8,21394.8,318.4,1.203089,26146.8,98.796911
80,Frank Ocean,Male,United States,English,R&B,Solo,2011,24807.4,20425.4,4391.5,18809.3,75.821328,5998.1,24.178672
119,USHER,Male,United States,English,R&B,Solo,1994,18413.2,12525.4,5896.3,5222.1,28.360633,13191.1,71.639367
125,Kali Uchis,Female,Colombia,English,R&B,Solo,2012,18005.3,10367.0,7646.6,7259.1,40.316462,10746.2,59.683538
134,Akon,Male,Senegal,English,R&B,Solo,2004,17056.0,8007.4,9059.5,4403.1,25.815549,12652.9,74.184451
154,Daniel Caesar,Male,Canada,English,R&B,Solo,2014,15876.2,12905.1,2982.4,7353.2,46.315869,8523.0,53.684131
174,Ne-Yo,Male,United States,English,R&B,Solo,2006,14888.6,8808.5,6090.2,8012.0,53.812984,6876.6,46.187016
178,Joji,Male,Japan,English,R&B,Solo,2017,14512.1,13579.3,938.4,12111.7,83.459320,2400.4,16.540680
180,PARTYNEXTDOOR,Male,Canada,English,R&B,Solo,2013,14506.3,13237.2,1275.0,7177.2,49.476434,7329.1,50.523566
198,Bryson Tiller,Male,United States,English,R&B,Solo,2011,13890.6,13739.5,155.6,8915.5,64.183693,4975.1,35.816307
206,Brent Faiyaz,Male,United States,English,R&B,Solo,2013,13490.4,9955.4,3540.8,8582.9,63.622280,4907.5,36.377720
219,Miguel,Male,United States,English,R&B,Solo,2010,13065.7,7612.4,5460.1,5541.7,42.414107,7524.0,57.585893
247,Alicia Keys,Female,United States,English,R&B,Solo,2001,12099.6,8350.5,3754.7,7341.3,60.673907,4758.3,39.326093
252,John Legend,Male,United States,English,R&B,Solo,2004,11821.6,7454.6,4369.1,5783.2,48.920620,6038.4,51.079380
267,blackbear,Male,United States,English,R&B,Solo,2006,11428.5,7562.2,3868.0,6108.9,53.453209,5319.6,46.546791
269,T-Pain,Male,United States,English,R&B,Solo,2005,11238.2,4609.5,6628.7,839.9,7.473617,10398.3,92.526383
291,Summer Walker,Female,United States,English,R&B,Solo,2018,10756.4,7776.1,2980.3,3834.9,35.652263,6921.5,64.347737
292,Jhené Aiko,Female,United States,English,R&B,Solo,2002,10731.7,6224.9,4506.8,3239.2,30.183475,7492.5,69.816525
293,Kehlani,Female,United States,English,R&B,Solo,2014,10712.8,6060.2,4663.4,4257.4,39.741244,6455.4,60.258756
302,Steve Lacy,Male,United States,English,R&B,Solo,2015,10368.7,9179.2,1201.2,8970.6,86.516150,1398.1,13.483850
335,Jeremih,Male,United States,English,R&B,Solo,2009,9713.0,5586.8,4126.1,2334.8,24.037887,7378.2,75.962113
338,Anderson .Paak,Male,United States,English,R&B,Solo,2014,9513.7,9454.3,63.4,1289.2,13.550984,8224.5,86.449016
339,Chase Atlantic,Male,Australia,English,R&B,Group,2014,9513.0,9329.3,185.8,8793.0,92.431410,720.0,7.568590
348,GIVĒON,Male,United States,English,R&B,Solo,2018,9302.9,5809.3,3497.2,5699.0,61.260467,3603.9,38.739533
370,Whitney Houston,Female,United States,English,R&B,Solo,1985,8828.8,7564.4,1267.8,6762.6,76.597046,2066.2,23.402954
440,6LACK,Male,United States,English,R&B,Solo,2016,7810.5,3575.2,4235.2,2342.1,29.986557,5468.4,70.013443
454,H.E.R.,Female,United States,English,R&B,Solo,2016,7608.2,3801.5,3806.7,2191.8,28.808391,5416.4,71.191609

In [21]:
df[df["Primary Genre"].isin(["Pop", "R&B"])].head(10)

,Artist Name,Sex,Country of Origin,Primary Language,Primary Genre,Artist Type,Debut Year,Total Streams (in millions),Lead Streams (in millions),Feature Streams (in millions),Solo Streams (in millions),% of Solo Streams,Collaborative Streams (in millions),% of Collaborative Streams
1,Taylor Swift,Female,United States,English,Pop,Solo,2006,127861.0,126177.3,1683.8,113421.5,88.706877,14439.5,11.293123
3,The Weeknd,Male,Canada,English,R&B,Solo,2009,95703.2,77189.4,18513.8,51020.0,53.310652,44683.2,46.689348
4,Justin Bieber,Male,Canada,English,Pop,Solo,2009,78104.4,48316.2,29788.2,29638.3,37.947030,48466.1,62.052970
5,Ariana Grande,Female,United States,English,Pop,Solo,2013,68298.9,57097.5,11201.4,41615.5,60.931435,26683.4,39.068565
8,Ed Sheeran,Male,United Kingdom,English,Pop,Solo,2011,64656.9,57704.0,6967.8,46700.0,72.227403,17956.9,27.772597
10,Rihanna,Female,Barbados,English,Pop,Solo,2005,60670.7,44824.4,15846.4,30261.8,49.878772,30408.9,50.121228
11,Billie Eilish,Female,United States,English,Pop,Solo,2015,58049.5,57160.1,889.4,51567.9,88.834357,6481.6,11.165643
12,Bruno Mars,Male,United States,English,Pop,Solo,2010,56727.1,40714.0,16013.1,33618.1,59.262857,23109.0,40.737143
14,Post Malone,Male,United States,English,Pop,Solo,2011,55028.3,48805.6,6235.6,25419.4,46.193322,29608.9,53.806678
21,Chris Brown,Male,United States,English,R&B,Solo,2005,43963.8,24455.7,19523.9,12219.3,27.794003,31744.5,72.205997

In [24]:
df.sort_values(by="Total Streams (in millions)", ascending=False)

,Artist Name,Sex,Country of Origin,Primary Language,Primary Genre,Artist Type,Debut Year,Total Streams (in millions),Lead Streams (in millions),Feature Streams (in millions),Solo Streams (in millions),% of Solo Streams,Collaborative Streams (in millions),% of Collaborative Streams
0,Drake,Male,Canada,English,Hip-Hop,Solo,2006,137492.1,94851.1,42640.9,53323.9,38.783246,84168.2,61.216754
1,Taylor Swift,Female,United States,English,Pop,Solo,2006,127861.0,126177.3,1683.8,113421.5,88.706877,14439.5,11.293123
2,Bad Bunny,Male,United States,Spanish,Reggaeton,Solo,2013,125899.8,82189.3,43710.5,48887.0,38.830086,77012.8,61.169914
3,The Weeknd,Male,Canada,English,R&B,Solo,2009,95703.2,77189.4,18513.8,51020.0,53.310652,44683.2,46.689348
4,Justin Bieber,Male,Canada,English,Pop,Solo,2009,78104.4,48316.2,29788.2,29638.3,37.947030,48466.1,62.052970
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,The Cure,Male,United Kingdom,English,Rock,Group,1979,7034.1,7035.0,3.3,6940.1,98.663653,94.0,1.336347
496,The Marías,Mixed,United States,English,Pop,Group,2017,7029.1,5774.4,1261.4,5705.9,81.175399,1323.2,18.824601
497,Limp Bizkit,Male,United States,English,Nu Metal,Group,1997,7018.9,7018.4,5.4,6806.0,96.966761,212.9,3.033239
498,Korn,Male,United States,English,Metal,Group,1994,6976.4,4188.4,2798.5,6414.9,91.951436,561.5,8.048564
499,Omar Courtz,Male,United States,Spanish,Reggaeton,Solo,2017,6972.0,6956.0,20.3,1876.2,26.910499,5095.8,73.089501

In [29]:
df[(df["Primary Genre"].isin(["Pop", "R&B", "Dance"])) & (df["Total Streams (in millions)"] > 500) & (df["Debut Year"] < 2010)]

,Artist Name,Sex,Country of Origin,Primary Language,Primary Genre,Artist Type,Debut Year,Total Streams (in millions),Lead Streams (in millions),Feature Streams (in millions),Solo Streams (in millions),% of Solo Streams,Collaborative Streams (in millions),% of Collaborative Streams
1,Taylor Swift,Female,United States,English,Pop,Solo,2006,127861.0,126177.3,1683.8,113421.5,88.706877,14439.5,11.293123
3,The Weeknd,Male,Canada,English,R&B,Solo,2009,95703.2,77189.4,18513.8,51020.0,53.310652,44683.2,46.689348
4,Justin Bieber,Male,Canada,English,Pop,Solo,2009,78104.4,48316.2,29788.2,29638.3,37.947030,48466.1,62.052970
10,Rihanna,Female,Barbados,English,Pop,Solo,2005,60670.7,44824.4,15846.4,30261.8,49.878772,30408.9,50.121228
21,Chris Brown,Male,United States,English,R&B,Solo,2005,43963.8,24455.7,19523.9,12219.3,27.794003,31744.5,72.205997
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
459,Céline Dion,Female,Canada,French,Pop,Solo,1981,7543.1,7093.1,450.0,6268.7,83.105089,1274.4,16.894911
476,MØ,Female,Denmark,English,Pop,Solo,2006,7335.2,6735.6,602.0,1341.8,18.292616,5993.4,81.707384
483,Magenta,Female,Italy,Italian,Pop,Solo,1997,7239.7,0.0,7239.7,0.0,0.000000,7239.7,100.000000
489,benny blanco,Male,United States,English,Pop,Solo,2007,7114.1,4400.3,2716.0,3.9,0.054821,7110.2,99.945179
494,Jason Mraz,Male,United States,English,Pop,Solo,2002,7048.5,6851.4,199.1,5805.0,82.357949,1243.5,17.642052

In [46]:
df[(df["Sex"] == "Male") & df["Primary Genre"].isin(["Hip Hop", "Pop", "R&B"]) & (df["Total Streams (in millions)"] > 500)]

,Artist Name,Sex,Country of Origin,Primary Language,Primary Genre,Artist Type,Debut Year,Total Streams (in millions),Lead Streams (in millions),Feature Streams (in millions),Solo Streams (in millions),% of Solo Streams,Collaborative Streams (in millions),% of Collaborative Streams
3,The Weeknd,Male,Canada,English,R&B,Solo,2009,95703.2,77189.4,18513.8,51020.0,53.310652,44683.2,46.689348
4,Justin Bieber,Male,Canada,English,Pop,Solo,2009,78104.4,48316.2,29788.2,29638.3,37.947030,48466.1,62.052970
8,Ed Sheeran,Male,United Kingdom,English,Pop,Solo,2011,64656.9,57704.0,6967.8,46700.0,72.227403,17956.9,27.772597
12,Bruno Mars,Male,United States,English,Pop,Solo,2010,56727.1,40714.0,16013.1,33618.1,59.262857,23109.0,40.737143
14,Post Malone,Male,United States,English,Pop,Solo,2011,55028.3,48805.6,6235.6,25419.4,46.193322,29608.9,53.806678
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
464,LANY,Male,United States,English,Pop,Group,2014,7453.2,2524.9,4942.4,6424.3,86.195191,1028.9,13.804809
473,Tom Odell,Male,United Kingdom,English,Pop,Solo,2012,7352.6,3894.0,3483.8,6069.3,82.546310,1283.3,17.453690
486,Calum Scott,Male,United Kingdom,English,Pop,Solo,2016,7192.6,4689.2,2505.3,3982.2,55.365236,3210.4,44.634764
489,benny blanco,Male,United States,English,Pop,Solo,2007,7114.1,4400.3,2716.0,3.9,0.054821,7110.2,99.945179
494,Jason Mraz,Male,United States,English,Pop,Solo,2002,7048.5,6851.4,199.1,5805.0,82.357949,1243.5,17.642052

In [41]:
df[
    (df["Primary Genre"].isin(["Hip Hop", "R&B", "Pop"])) &
    (df["Debut Year"] > 2010) &
    (df["Total Streams (in millions)"] > 2000)
]

,Artist Name,Sex,Country of Origin,Primary Language,Primary Genre,Artist Type,Debut Year,Total Streams (in millions),Lead Streams (in millions),Feature Streams (in millions),Solo Streams (in millions),% of Solo Streams,Collaborative Streams (in millions),% of Collaborative Streams
5,Ariana Grande,Female,United States,English,Pop,Solo,2013,68298.9,57097.5,11201.4,41615.5,60.931435,26683.4,39.068565
8,Ed Sheeran,Male,United Kingdom,English,Pop,Solo,2011,64656.9,57704.0,6967.8,46700.0,72.227403,17956.9,27.772597
11,Billie Eilish,Female,United States,English,Pop,Solo,2015,58049.5,57160.1,889.4,51567.9,88.834357,6481.6,11.165643
14,Post Malone,Male,United States,English,Pop,Solo,2011,55028.3,48805.6,6235.6,25419.4,46.193322,29608.9,53.806678
25,Dua Lipa,Female,United Kingdom,English,Pop,Solo,2015,41944.1,28269.7,13687.6,23133.7,55.153645,18810.4,44.846355
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
464,LANY,Male,United States,English,Pop,Group,2014,7453.2,2524.9,4942.4,6424.3,86.195191,1028.9,13.804809
473,Tom Odell,Male,United Kingdom,English,Pop,Solo,2012,7352.6,3894.0,3483.8,6069.3,82.546310,1283.3,17.453690
479,Laufey,Female,Iceland,English,Pop,Solo,2020,7286.8,4703.7,2609.5,6083.2,83.482461,1203.6,16.517539
486,Calum Scott,Male,United Kingdom,English,Pop,Solo,2016,7192.6,4689.2,2505.3,3982.2,55.365236,3210.4,44.634764
496,The Marías,Mixed,United States,English,Pop,Group,2017,7029.1,5774.4,1261.4,5705.9,81.175399,1323.2,18.824601

In [42]:
df.isnull()

,Artist Name,Sex,Country of Origin,Primary Language,Primary Genre,Artist Type,Debut Year,Total Streams (in millions),Lead Streams (in millions),Feature Streams (in millions),Solo Streams (in millions),% of Solo Streams,Collaborative Streams (in millions),% of Collaborative Streams
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,False,False,False,False,False,False,False,False,False,False,False,False,False,False
496,False,False,False,False,False,False,False,False,False,False,False,False,False,False
497,False,False,False,False,False,False,False,False,False,False,False,False,False,False
498,False,False,False,False,False,False,False,False,False,False,False,False,False,False
499,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [43]:
df = df.dropna()

In [47]:
df["Lead Streams (in millions)"].mean()

np.float64(12141.734000000002)

In [48]:
df["Primary Genre"].value_counts()

Primary Genre
Hip-Hop             115
Pop                 102
Rock                 60
Reggaeton            43
R&B                  31
Latin                30
EDM                  22
Regional Mexican     19
K-Pop                11
Filmi                11
Country              10
Alternative           9
Sertanjeo             9
Metal                 8
Folk                  4
Soundtrack            3
Bachata               3
Soul                  3
Reggae                2
Afrobeats             2
Spoken Word           1
Children's Music      1
Nu Metal              1
Name: count, dtype: int64

In [52]:
country_counts = df["Country of Origin"].value_counts()
selected_countries = country_counts[country_counts > 1].index

df[(df["Country of Origin"].isin(selected_countries)) & (df["Total Streams (in millions)"] > 1000)]

,Artist Name,Sex,Country of Origin,Primary Language,Primary Genre,Artist Type,Debut Year,Total Streams (in millions),Lead Streams (in millions),Feature Streams (in millions),Solo Streams (in millions),% of Solo Streams,Collaborative Streams (in millions),% of Collaborative Streams
0,Drake,Male,Canada,English,Hip-Hop,Solo,2006,137492.1,94851.1,42640.9,53323.9,38.783246,84168.2,61.216754
1,Taylor Swift,Female,United States,English,Pop,Solo,2006,127861.0,126177.3,1683.8,113421.5,88.706877,14439.5,11.293123
2,Bad Bunny,Male,United States,Spanish,Reggaeton,Solo,2013,125899.8,82189.3,43710.5,48887.0,38.830086,77012.8,61.169914
3,The Weeknd,Male,Canada,English,R&B,Solo,2009,95703.2,77189.4,18513.8,51020.0,53.310652,44683.2,46.689348
4,Justin Bieber,Male,Canada,English,Pop,Solo,2009,78104.4,48316.2,29788.2,29638.3,37.947030,48466.1,62.052970
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,The Cure,Male,United Kingdom,English,Rock,Group,1979,7034.1,7035.0,3.3,6940.1,98.663653,94.0,1.336347
496,The Marías,Mixed,United States,English,Pop,Group,2017,7029.1,5774.4,1261.4,5705.9,81.175399,1323.2,18.824601
497,Limp Bizkit,Male,United States,English,Nu Metal,Group,1997,7018.9,7018.4,5.4,6806.0,96.966761,212.9,3.033239
498,Korn,Male,United States,English,Metal,Group,1994,6976.4,4188.4,2798.5,6414.9,91.951436,561.5,8.048564
499,Omar Courtz,Male,United States,Spanish,Reggaeton,Solo,2017,6972.0,6956.0,20.3,1876.2,26.910499,5095.8,73.089501

In [54]:
df["Total Streams (in millions)"].std()

np.float64(14845.19763175849)

In [58]:
# Compute percentage change for the first 10 total-stream rows
stream_pct = df["Total Streams (in millions)"].pct_change().head(10)
# Count artist occurrences
artist_counts = df["Artist Name"].value_counts()

stream_pct
artist_counts

Artist Name
Drake            1
Taylor Swift     1
Bad Bunny        1
The Weeknd       1
Justin Bieber    1
                ..
The Cure         1
The Marías       1
Limp Bizkit      1
Korn             1
Omar Courtz      1
Name: count, Length: 500, dtype: int64

In [63]:
df[df['Primary Genre'] == 'Pop']

,Artist Name,Sex,Country of Origin,Primary Language,Primary Genre,Artist Type,Debut Year,Total Streams (in millions),Lead Streams (in millions),Feature Streams (in millions),Solo Streams (in millions),% of Solo Streams,Collaborative Streams (in millions),% of Collaborative Streams
1,Taylor Swift,Female,United States,English,Pop,Solo,2006,127861.0,126177.3,1683.8,113421.5,88.706877,14439.5,11.293123
4,Justin Bieber,Male,Canada,English,Pop,Solo,2009,78104.4,48316.2,29788.2,29638.3,37.947030,48466.1,62.052970
5,Ariana Grande,Female,United States,English,Pop,Solo,2013,68298.9,57097.5,11201.4,41615.5,60.931435,26683.4,39.068565
8,Ed Sheeran,Male,United Kingdom,English,Pop,Solo,2011,64656.9,57704.0,6967.8,46700.0,72.227403,17956.9,27.772597
10,Rihanna,Female,Barbados,English,Pop,Solo,2005,60670.7,44824.4,15846.4,30261.8,49.878772,30408.9,50.121228
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
483,Magenta,Female,Italy,Italian,Pop,Solo,1997,7239.7,0.0,7239.7,0.0,0.000000,7239.7,100.000000
486,Calum Scott,Male,United Kingdom,English,Pop,Solo,2016,7192.6,4689.2,2505.3,3982.2,55.365236,3210.4,44.634764
489,benny blanco,Male,United States,English,Pop,Solo,2007,7114.1,4400.3,2716.0,3.9,0.054821,7110.2,99.945179
494,Jason Mraz,Male,United States,English,Pop,Solo,2002,7048.5,6851.4,199.1,5805.0,82.357949,1243.5,17.642052
496,The Marías,Mixed,United States,English,Pop,Group,2017,7029.1,5774.4,1261.4,5705.9,81.175399,1323.2,18.824601

In [67]:
df.pivot_table(index='Primary Genre', values='Total Streams (in millions)' ,columns='Sex', aggfunc='mean')

Sex                     Female          Male         Mixed
Primary Genre
Afrobeats                  NaN  10719.800000           NaN
Alternative       26701.750000  13589.466667  13287.000000
Bachata                    NaN  13550.466667           NaN
Children's Music   8316.500000           NaN           NaN
Country                    NaN  13028.620000           NaN
EDM                        NaN  16851.261905  13220.400000
Filmi             12355.600000  14071.855556           NaN
Folk                       NaN   9841.700000           NaN
Hip-Hop           26452.400000  18396.130000  11561.800000
K-Pop             11544.325000  17105.016667   8531.300000
Latin             15482.675000  12327.696000   7838.900000
Metal                      NaN   9199.862500           NaN
Nu Metal                   NaN   7018.900000           NaN
Pop               20621.601818  18608.237500  17869.171429
R&B               14702.800000  19698.956522           NaN
Reggae                     NaN  16598.000000           NaN
Reggaeton         23254.900000  20545.007317           NaN
Regional Mexican           NaN  13474.394737           NaN
Rock               8476.900000  13410.950980  15881.471429
Sertanjeo         10127.966667  12402.416667           NaN
Soul               8336.650000   8371.500000           NaN
Soundtrack                 NaN   8906.900000  16142.200000
Spoken Word                NaN  24607.000000           NaN

In [69]:
df[df["Artist Name"] == "Akon"].head(10)

,Artist Name,Sex,Country of Origin,Primary Language,Primary Genre,Artist Type,Debut Year,Total Streams (in millions),Lead Streams (in millions),Feature Streams (in millions),Solo Streams (in millions),% of Solo Streams,Collaborative Streams (in millions),% of Collaborative Streams
134,Akon,Male,Senegal,English,R&B,Solo,2004,17056.0,8007.4,9059.5,4403.1,25.815549,12652.9,74.184451

In [70]:
plt.figure(figsize=(10, 6))

In [71]:
df[df["Artist Name"] == "Justin Bieber"].head(10)

,Artist Name,Sex,Country of Origin,Primary Language,Primary Genre,Artist Type,Debut Year,Total Streams (in millions),Lead Streams (in millions),Feature Streams (in millions),Solo Streams (in millions),% of Solo Streams,Collaborative Streams (in millions),% of Collaborative Streams
4,Justin Bieber,Male,Canada,English,Pop,Solo,2009,78104.4,48316.2,29788.2,29638.3,37.94703,48466.1,62.05297